# .streamlit/secrets.toml

#[connections.snowpark]
[snowflake]
account = "lifesphere-datahub_preview"
user = "streamlit_svc"
password = "saI_Ram__2423!"
role = "SYSADMIN"
warehouse = "COMPUTE_EXTRASMALL"
database = "AG_ADMIN_DB"
schema = "PUBLIC"
client_session_keep_alive = true
