name: python

on: 

  workflow_dispatch:

env:
         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
         SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
         SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/checkout@v3
      with:
        python-version: '3.8'
    - name: Run Python
      run:
         pip install -r requirements.txt
         python streamlitapp.py
     
    
